version: "2"

services:
  chowdown:
    image: jekyll/jekyll
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - /mnt/data/docker/volumes/Chowdown/_data/components:/srv/jekyll/_components
      - /mnt/data/docker/volumes/Chowdown/_data/images:/srv/jekyll/_images
      - /mnt/data/docker/volumes/Chowdown/_data/posts:/srv/jekyll/_posts
      - /mnt/data/docker/volumes/Chowdown/_data/recipes:/srv/jekyll/_recipes
